# -*- coding: utf-8 -*-
"""20231004.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16qMzwwA5N-xxHKGoiQTbYkkrLrgMldu9
"""

import requests
url = 'https://irs.thsrc.com.tw/IMINT/'
# 自訂表頭
headers = {'user-agent': 'Mozilla/5.0 (Linux; Android 8.0.0; \
      SM-G960F Build/R16NW) AppleWebkit \
     /537.36(KHTML, like Gecko) \
     Chrome/62.0.3202.84 Mobile Safari/537.36'
}
# 將自訂表頭加入 GET 請求中
html = requests.get(url, headers=headers)
print(html)